workflows:
  testFlight:
    name: "Ios Release"
    integrations:
      app_store_connect: ZOUHAIR MOUFARAJ
    environment:
      flutter: 3.41.0
      ios_signing:
        provisioning_profiles:
          - provisioning_SockslitePro
        certificates:
          - Certificate_zouhir
    scripts:
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Get Flutter packages
        script: flutter packages pub get
      - name: Set up code signing
        script: xcode-project use-profiles
      - name: Build IPA
        script: flutter build ipa --release --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - moufarijamix50@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration


